name: sen
description: 'Sen: Environment'
publish_to: 'none'
version: 2.0.0
environment:
    sdk: '>=3.7.0 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    window_manager: ^0.4.3
    desktop_drop: ^0.5.0
    nil: ^1.1.1
    matrix4_transform: ^4.0.1
    pie_menu: ^3.2.7
    uuid: ^4.5.1
    custom_mouse_cursor: ^1.1.2
    loading_animation_widget: ^1.3.0
    equatable: ^2.0.7
    screenshot: ^3.0.0
    flutter_fancy_tree_view: ^1.6.0
    ffi: ^2.1.4
    path: ^1.9.1
    flutter_native_splash: ^2.4.5
    drop_down_search_field: ^1.1.2+2
    meta: ^1.16.0
    async: ^2.12.0
    image: ^4.5.3
    flutter_localizations:
        sdk: flutter
    archive: ^4.0.4
    bloc: ^9.0.0
    intl: ^0.19.0
    file_selector: ^1.0.3
    path_provider: ^2.1.5
    shared_preferences: ^2.5.2
    url_launcher: ^6.3.1
    dio: ^5.8.0+1
    flex_color_picker: ^3.7.0
    flutter_bloc: ^9.1.0
    dynamic_color: ^1.7.0
    nested: ^1.0.0
    audioplayers: ^6.4.0
    material_symbols_icons: ^4.2810.1
    flutter_local_notifications: ^19.0.0
    collection: ^1.19.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    msix: ^3.16.8
    flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
    android: true
    ios: true
    window: true
    linux: true
    macintosh: true
    image_path: 'assets/images/logo.png'
    remove_alpha_ios: true
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/images/translator/
    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/font/GoogleSans-Regular.ttf
        - family: Segoe UI
          fonts:
              - asset: assets/font/SegoeUI.ttf
        - family: PVZ2Font
          fonts:
              - asset: assets/font/fbUsv8C5eI.ttf
msix_config:
    display_name: Sen
    publisher_display_name: Haruma
    identity_name: com.haruma.sen.environment
    publisher: CN=Haruma
    architecture: x64
    logo_path: assets/images/logo.png
    install_certificate: false
    author: Haruma
    files:
        - source: ./windows/explorer/build/Release/explorer.dll
          target: explorer.dll
        - source: ./windows/virtual/build/Release/virtual.exe
          target: virtual.exe
    declarations:
        - comServer
    applications:
        - id: DLLHost
          executable: virtual.exe
          entryPoint: Windows.FullTrustApplication
    app_installer:
        publish_folder_path: ./publish
        hours_between_update_checks: 0
        automatic_background_task: true
        update_blocks_activation: true
        show_prompt: true
        force_update_from_any_version: true
    certificate_path: ./certificate.pfx
    certificate_password: haruma123
    scripts:
        on_install: register_context_menu.ps1
